patchedDependencies:
  function-plot: patches/function-plot.patch
  katex: patches/katex.patch

overrides:
  esbuild: ^0.25.0
  lodash-es: ^4.17.23

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
